"""AST deny-list policy tables and resource limits for code execution.

Not an OS sandbox — see ``code_exec.py`` module docstring.
"""

from __future__ import annotations

_BLOCKED_MODULES = frozenset(
    {
        "operator",
        "_operator",
        "functools",
        "_functools",
        "copy",
        "weakref",
        "os",
        "subprocess",
        "socket",
        "shutil",
        "ctypes",
        "multiprocessing",
        "pickle",
        "builtins",
        "importlib",
        "importlib.util",
        "pty",
        "fcntl",
        "resource",
        "signal",
        "pathlib",
        "sys",
        "io",
        "code",
        "gc",
        "inspect",
        "types",
        "glob",
        "tempfile",
        "sqlite3",
        "http",
        "urllib",
        "requests",
        "webbrowser",
        "site",
        "runpy",
        "_io",
        "ssl",
        "ftplib",
        "smtplib",
        "marshal",
        "select",
        "selectors",
        "threading",
        "asyncio",
        "email",
        "zipfile",
        "tarfile",
        "gzip",
        "bz2",
        "lzma",
        "binascii",
        "struct",
        "array",
        "mmap",
        "msvcrt",
        "winreg",
        "winsound",
        "posix",
        "pwd",
        "grp",
        "termios",
        "tty",
        "readline",
        "curses",
        "dbm",
        "shelve",
        "xmlrpc",
        "xml",
        "html",
        "nntplib",
        "poplib",
        "imaplib",
        "telnetlib",
        "aifc",
        "sunau",
        "wave",
        "chunk",
        "colorsys",
        "crypt",
        "hmac",
        "secrets",
        "uuid",
        "venv",
        "ensurepip",
        "pip",
        "setuptools",
        "distutils",
        "configparser",
        "logging",
        "warnings",
        "traceback",
        "linecache",
        "dis",
        "pickletools",
        "doctest",
        "unittest",
        "pdb",
        "profile",
        "pstats",
        "timeit",
        "trace",
        "tracemalloc",
        "faulthandler",
        "atexit",
        "symtable",
        "tokenize",
        "keyword",
        "token",
        "ast",
        "parser",
        "symbol",
        "tabnanny",
        "py_compile",
        "compileall",
        "zipimport",
        "pkgutil",
        "modulefinder",
        "imp",
    }
)
_BLOCKED_NAMES = frozenset(
    {
        "eval",
        "exec",
        "compile",
        "open",
        "__import__",
        "breakpoint",
        "getattr",
        "setattr",
        "delattr",
        "hasattr",
        "type",
        "object",
        "classmethod",
        "staticmethod",
        "super",
        "vars",
        "input",
        "globals",
        "locals",
        "memoryview",
        "bytearray",
        "bytes",
        "help",
        "dir",
        "property",
        "__build_class__",
    }
)
_BLOCKED_ATTRS = frozenset(
    {
        "gi_frame",
        "gi_code",
        "gi_yieldfrom",
        "f_back",
        "f_builtins",
        "f_globals",
        "f_locals",
        "f_code",
        "cr_frame",
        "tb_frame",
        "tb_next",
        "__class__",
        "__bases__",
        "__subclasses__",
        "__mro__",
        "__init__",
        "__globals__",
        "__code__",
        "__builtins__",
        "__dict__",
        "__getattribute__",
        "__reduce__",
        "__reduce_ex__",
    }
)
_TIMEOUT_SEC = 15
_MAX_OUTPUT = 16_000
_MAX_CODE_LEN = 8_000
_MAX_RSS_BYTES = 256 * 1024 * 1024
_MAX_OPEN_FDS = 32
_MAX_ALLOC_SIZE = 1_000_000
_ALLOWED_MODULES = frozenset(
    {
        "math",
        "re",
        "statistics",
        "datetime",
        "collections",
        "itertools",
        "json",
        "decimal",
        "fractions",
        "random",
        "string",
        "textwrap",
        "bisect",
        "heapq",
        "numbers",
        "cmath",
        "dataclasses",
    }
)


def import_blocked(module: str) -> bool:
    """Allow only a small stdlib subset; block underscore and dangerous modules."""
    root = module.split(".")[0]
    if root.startswith("_"):
        return True
    if root in _BLOCKED_MODULES:
        return True
    stripped = root.lstrip("_")
    if stripped and stripped in _BLOCKED_MODULES:
        return True
    return root not in _ALLOWED_MODULES
